- common/component/src/main/java/io/fasthome/component/personality_data/PersonalityComponentFragment.kt
- common/component/src/main/java/io/fasthome/component/personality_data/PersonalityComponentViewModel.kt
- common/component/src/main/res/layout/fragment_personality_component.xml
- common/uikit/src/main/res/values/strings.xml
- common/util/src/main/java/io/fasthome/fenestram_messenger/util/RegexFilters.kt
- common/util/src/main/java/io/fasthome/fenestram_messenger/util/SpacesToUnderscoresInputFilter.kt
- common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/Extension.kt
- common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/LinkBuilder.kt
- common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/RegexLinkPatterns.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationEvent.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/adapter/ConversationAdapter.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/adapter/TagParticipantsAdapter.kt
- features/messenger/messenger-impl/src/main/res/layout/fragment_conversation.xml
- features/messenger/messenger-impl/src/main/res/layout/item_user_tag.xml
Содержит ветку [feature/GLOBAL-1173](https://github.com/fasthome/Android-Fenestram-Messenger/tree/feature/GLOBAL-1173), не мержить, пока не замержат её!
> GLOBAL-1516 Исправления в редактировании никнейма в профиле

- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/InputMessageMode.kt
При удалении сообщения со стороны юзера
При удалении сообщения со стороны собеседника
> GLOBAL-1465 Выключение режима редактирования/ответа при удалении сообщения

- common/data/src/main/java/io/fasthome/fenestram_messenger/data/CoreStorage.kt
- common/data/src/main/java/io/fasthome/fenestram_messenger/data/UserStorage.kt
- common/data/src/main/java/io/fasthome/fenestram_messenger/data/core/CoreRepo.kt
- common/data/src/main/java/io/fasthome/fenestram_messenger/data/core/CoreRepoImpl.kt
- features/auth/auth-impl/build.gradle.kts
- features/auth/auth-impl/src/main/java/io/fasthome/fenestram_messenger/auth_impl/domain/logic/ClearUserDataUseCase.kt
- features/messenger/messenger-api/src/main/java/io/fasthome/fenestram_messenger/messenger_api/MessengerFeature.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/MessengerFeatureImpl.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/data/repo_impl/FilesRepoImpl.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/domain/logic/MessengerInteractor.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/domain/repo/FilesRepo.kt
> GLOBAL-1225 Очистка Shared preference и CameraFileStorage при выходе из учетной записи

- features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/data/service/ContactsService.kt
- features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/presentation/contacts/ContactsViewModel.kt
- features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/presentation/contacts/adapter/ContactsAdapter.kt
> GLOBAL-1660 Исправление дублирования контактов при добавлении

- common/component/src/main/java/io/fasthome/component/personality_data/SpaceInputFilter.kt
Убрал строку из фильтра, вроде бага нет и ничего не поломалось
> GLOBAL-1774  Баг при вводе имени и никнейма

- common/presentation/base/src/main/java/io/fasthome/fenestram_messenger/presentation/base/ui/BottomSheetFragment.kt
- features/contacts/contacts-api/src/main/java/io/fasthome/fenestram_messenger/contacts_api/ContactsFeature.kt
- features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/ContactsFeatureImpl.kt
- features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/data/ContactsLoader.kt
- features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/data/repo_impl/ContactsRepoImpl.kt
- features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/data/service/ContactsService.kt
- features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/data/service/model/UpdateContactNameRequest.kt
- features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/domain/logic/ContactsInteractor.kt
- features/contacts/contacts-impl/src/main/java/io/fasthome/fenestram_messenger/contacts_impl/domain/repo/ContactsRepo.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
- features/profile-guest/profile-guest-api/src/main/java/io/fasthome/fenestram_messenger/profile_guest_api/ProfileGuestFeature.kt
- features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/ProfileGuestFeatureImpl.kt
- features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/presentation/profile_guest/ProfileGuestFragment.kt
- features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/presentation/profile_guest/ProfileGuestNavigationContract.kt
- features/profile-guest/profile-guest-impl/src/main/java/io/fasthome/fenestram_messenger/profile_guest_impl/presentation/profile_guest/ProfileGuestViewModel.kt
… при его отсутствии, возврат результата через BottomSheetFragment
> GLOBAL-1779 Исправление изменения имени контакта, добавление контакта при его отсутствии, возврат результата через BottomSheetFragment

- features/auth/auth-impl/src/main/java/io/fasthome/fenestram_messenger/auth_impl/presentation/code/CodeEvent.kt
- features/auth/auth-impl/src/main/java/io/fasthome/fenestram_messenger/auth_impl/presentation/code/CodeFragment.kt
- features/auth/auth-impl/src/main/java/io/fasthome/fenestram_messenger/auth_impl/presentation/code/CodeState.kt
- features/auth/auth-impl/src/main/java/io/fasthome/fenestram_messenger/auth_impl/presentation/code/CodeViewModel.kt
- features/auth/auth-impl/src/main/res/layout/fragment_code.xml
- features/auth/auth-impl/src/main/res/values/strings.xml
https://softworks.kaiten.ru/8587931
> #8587931 Обновление для экрана подтверждения кода

- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
https://softworks.kaiten.ru/space/19357/card/8860682?filter=eyJrZXkiOiJhbmQiLCJ2YWx1ZSI6W3sia2V5IjoiYW5kIiwidmFsdWUiOlt7ImtleSI6InRhZyIsImNvbXBhcmlzb24iOiJlcSIsInZhbHVlIjoyNTczOTF9XX1dfQ
> HC-8860682 Разделение сообщений по 5000 символов

- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationFragment.kt
https://softworks.kaiten.ru/space/19357/card/9460497?filter=eyJrZXkiOiJhbmQiLCJ2YWx1ZSI6W3sia2V5IjoiYW5kIiwidmFsdWUiOlt7ImtleSI6InRhZyIsImNvbXBhcmlzb24iOiJlcSIsInZhbHVlIjoyNTczOTF9XX1dfQ
> HC-9460497 Убрана возможность копировать изображение

- common/component/src/main/java/io/fasthome/component/profile_verification/ProfileVerificationContract.kt
- common/component/src/main/java/io/fasthome/component/profile_verification/ProfileVerificationEvent.kt
- common/component/src/main/java/io/fasthome/component/profile_verification/ProfileVerificationFragment.kt
- common/component/src/main/java/io/fasthome/component/profile_verification/ProfileVerificationState.kt
- common/component/src/main/java/io/fasthome/component/profile_verification/ProfileVerificationViewModel.kt
- common/component/src/main/res/layout/fragment_profile_verification.xml
- common/component/src/main/res/values/strings.xml
- common/uikit/src/main/res/drawable/ic_plus_with_bg_20.xml
- common/uikit/src/main/res/drawable/shape_bottom_line_1.xml
- common/uikit/src/main/res/values/button_styles.xml
- common/uikit/src/main/res/values/text_styles.xml
- features/debug/debug-impl/src/main/java/io/fasthome/fenestram_messenger/debug_impl/di/DebugModule.kt
- features/debug/debug-impl/src/main/java/io/fasthome/fenestram_messenger/debug_impl/presentation/debug/DebugFragment.kt
- features/debug/debug-impl/src/main/java/io/fasthome/fenestram_messenger/debug_impl/presentation/debug/DebugViewModel.kt
- features/debug/debug-impl/src/main/res/layout/fragment_debug.xml
https://softworks.kaiten.ru/space/19357/card/9505222?filter=eyJrZXkiOiJhbmQiLCJ2YWx1ZSI6W3sia2V5IjoiYW5kIiwidmFsdWUiOlt7ImtleSI6InRhZyIsImNvbXBhcmlzb24iOiJlcSIsInZhbHVlIjoyNTczOTF9XX1dfQ
> #9505222 Экран проверки профиля в дебаг меню

- common/presentation/base/src/main/java/io/fasthome/fenestram_messenger/presentation/base/ui/BaseBottomSheetFragment.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/adapter/TagParticipantsAdapter.kt
9427574 - https://softworks.kaiten.ru/space/19357/card/9427574
9461163 - https://softworks.kaiten.ru/space/19357/card/9461163
> Bugfix #9427574, #9461163 

- common/core/src/main/java/io/fasthome/fenestram_messenger/core/ui/extensions/ImageViewExt.kt
- features/camera/camera-impl/src/main/java/io/fasthome/fenestram_messenger/camera_impl/presentation/camera/CameraFragment.kt
- features/camera/camera-impl/src/main/java/io/fasthome/fenestram_messenger/camera_impl/presentation/camera/CameraViewModel.kt
- features/camera/camera-impl/src/main/java/io/fasthome/fenestram_messenger/camera_impl/presentation/confirm/ConfirmPhotoFragment.kt
- features/camera/camera-impl/src/main/res/layout/fragment_camera.xml
9430983 - https://softworks.kaiten.ru/space/19357/card/9430983
9144794 - https://softworks.kaiten.ru/space/19357/card/9144794
> Camera bugfix #9144794 #9430983

- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/data/MessengerSocket.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/domain/logic/MessengerInteractor.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/domain/repo/MessengerRepo.kt
- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/messenger/MessengerViewModel.kt
https://softworks.kaiten.ru/space/19357/card/9397495
> #9397495 Исправлен баг с входящими сообщениями в списке чатов

- common/component/src/main/java/io/fasthome/component/image_viewer/ImageViewerFragment.kt
- common/uikit/src/main/java/io/fasthome/fenestram_messenger/uikit/custom_view/PreCachingLayoutManager.kt
https://softworks.kaiten.ru/space/19357/card/9457173?filter=eyJrZXkiOiJhbmQiLCJ2YWx1ZSI6W3sia2V5IjoiYW5kIiwidmFsdWUiOlt7ImtleSI6InRhZyIsImNvbXBhcmlzb24iOiJlcSIsInZhbHVlIjoyNTczOTF9XX1dfQ
> HC-9457173 Предзагрузка следующего изображения в ImageViewer

- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
https://softworks.kaiten.ru/space/19357/card/9490435
> #9490435 Исправлено дублирование файлов

- features/messenger/messenger-impl/src/main/java/io/fasthome/fenestram_messenger/messenger_impl/presentation/conversation/ConversationViewModel.kt
https://softworks.kaiten.ru/space/19357/card/9683921?filter=eyJrZXkiOiJhbmQiLCJ2YWx1ZSI6W3sia2V5IjoiYW5kIiwidmFsdWUiOlt7ImtleSI6InRhZyIsImNvbXBhcmlzb24iOiJlcSIsInZhbHVlIjoyNTczOTF9XX1dfQ
> #9683921 Исправлена автоматическая установка пустых аватаров групп при создании чата

- features/profile/profile-impl/src/main/java/io/fasthome/fenestram_messenger/profile_impl/presentation/profile/ProfileFragment.kt
- features/profile/profile-impl/src/main/res/layout/fragment_profile.xml
https://softworks.kaiten.ru/space/19357/card/9778586?filter=eyJrZXkiOiJhbmQiLCJ2YWx1ZSI6W3sia2V5IjoiYW5kIiwidmFsdWUiOlt7ImtleSI6InRhZyIsImNvbXBhcmlzb24iOiJlcSIsInZhbHVlIjoyNTczOTF9XX1dfQ
> #9778586 пофикшен баг с  навигейшен бар при открытии из трея

- app/src/main/res/values/themes.xml
https://softworks.kaiten.ru/space/19357/card/9683642?filter=eyJrZXkiOiJhbmQiLCJ2YWx1ZSI6W3sia2V5IjoiYW5kIiwidmFsdWUiOlt7ImtleSI6InRhZyIsImNvbXBhcmlzb24iOiJlcSIsInZhbHVlIjoyNTczOTF9XX1dfQ
https://softworks.kaiten.ru/space/19357/card/9144498?filter=eyJrZXkiOiJhbmQiLCJ2YWx1ZSI6W3sia2V5IjoiYW5kIiwidmFsdWUiOlt7ImtleSI6InRhZyIsImNvbXBhcmlzb24iOiJlcSIsInZhbHVlIjoyNTczOTF9XX1dfQ
> #9144498, #9683642 Исправлено 2 темных темы и аватарки в негативе

- common/component/src/main/java/io/fasthome/component/file_selector/FileSelectorAdapter.kt
- common/component/src/main/java/io/fasthome/component/file_selector/FileSelectorFragment.kt
- common/component/src/main/res/layout/item_image_select_from.xml
- common/uikit/src/main/java/io/fasthome/fenestram_messenger/uikit/custom_view/GridAutofitLayoutManager.kt
https://softworks.kaiten.ru/space/19357/card/9457284?filter=eyJrZXkiOiJhbmQiLCJ2YWx1ZSI6W3sia2V5IjoiYW5kIiwidmFsdWUiOlt7ImtleSI6InRhZyIsImNvbXBhcmlzb24iOiJlcSIsInZhbHVlIjoyNTczOTF9XX1dfQ
Исправлены фризы при скролле списка изображений
> #9457284 Заменен FlexboxLayoutManager на кастомный GridAutofitLayoutManager

- common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/Extension.kt
- common/util/src/main/java/io/fasthome/fenestram_messenger/util/links/RegexLinkPatterns.kt
https://softworks.kaiten.ru/space/19357/card/9693908
> #9693908 Исправлено отображение веб ссылок с точками в конце
